#pragma once

#include <cstdint>
enum ZrMouseButton : uint32_t {
    ZR_MOUSE_BUTTON_1 = 0,
    ZR_MOUSE_BUTTON_2 = 1,
    ZR_MOUSE_BUTTON_3 = 2,
    ZR_MOUSE_BUTTON_4 = 3,
    ZR_MOUSE_BUTTON_5 = 4,
    ZR_MOUSE_BUTTON_6 = 5,
    ZR_MOUSE_BUTTON_7 = 6,
    ZR_MOUSE_BUTTON_8 = 7,
    ZR_MOUSE_BUTTON_LAST = ZR_MOUSE_BUTTON_8,
    ZR_MOUSE_BUTTON_LEFT = ZR_MOUSE_BUTTON_1,
    ZR_MOUSE_BUTTON_RIGHT = ZR_MOUSE_BUTTON_2,
    ZR_MOUSE_BUTTON_MIDDLE = ZR_MOUSE_BUTTON_3
};
