# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  ImGui_config = debug
  Glad_config = debug
  ImGuiFileDialog_config = debug
  SpdLog_config = debug
  yaml_cpp_config = debug
  Box2D_config = debug
  zirconium_config = debug
  zirconium_Editor_config = debug
endif
ifeq ($(config),release)
  GLFW_config = release
  ImGui_config = release
  Glad_config = release
  ImGuiFileDialog_config = release
  SpdLog_config = release
  yaml_cpp_config = release
  Box2D_config = release
  zirconium_config = release
  zirconium_Editor_config = release
endif
ifeq ($(config),dist)
  GLFW_config = dist
  ImGui_config = dist
  Glad_config = dist
  ImGuiFileDialog_config = dist
  SpdLog_config = dist
  yaml_cpp_config = dist
  Box2D_config = dist
  zirconium_config = dist
  zirconium_Editor_config = dist
endif

PROJECTS := GLFW ImGui Glad ImGuiFileDialog SpdLog yaml-cpp Box2D zirconium zirconium-Editor

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: Box2D GLFW Glad ImGui ImGuiFileDialog SpdLog yaml-cpp

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C zirconium/vendor/glfw -f Makefile config=$(GLFW_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C zirconium/vendor/imgui -f Makefile config=$(ImGui_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C zirconium/vendor/glad -f Makefile config=$(Glad_config)
endif

ImGuiFileDialog:
ifneq (,$(ImGuiFileDialog_config))
	@echo "==== Building ImGuiFileDialog ($(ImGuiFileDialog_config)) ===="
	@${MAKE} --no-print-directory -C zirconium/vendor/ImGuiFileDialog -f Makefile config=$(ImGuiFileDialog_config)
endif

SpdLog:
ifneq (,$(SpdLog_config))
	@echo "==== Building SpdLog ($(SpdLog_config)) ===="
	@${MAKE} --no-print-directory -C zirconium/vendor/spdlog -f Makefile config=$(SpdLog_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C zirconium/vendor/yaml-cpp -f Makefile config=$(yaml_cpp_config)
endif

Box2D:
ifneq (,$(Box2D_config))
	@echo "==== Building Box2D ($(Box2D_config)) ===="
	@${MAKE} --no-print-directory -C zirconium/vendor/Box2D -f Makefile config=$(Box2D_config)
endif

zirconium: GLFW Glad SpdLog ImGui Box2D yaml-cpp
ifneq (,$(zirconium_config))
	@echo "==== Building zirconium ($(zirconium_config)) ===="
	@${MAKE} --no-print-directory -C zirconium -f Makefile config=$(zirconium_config)
endif

zirconium-Editor: zirconium ImGuiFileDialog yaml-cpp Glad GLFW ImGui
ifneq (,$(zirconium_Editor_config))
	@echo "==== Building zirconium-Editor ($(zirconium_Editor_config)) ===="
	@${MAKE} --no-print-directory -C zirconium-Editor -f Makefile config=$(zirconium_Editor_config)
endif

clean:
	@${MAKE} --no-print-directory -C zirconium/vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C zirconium/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C zirconium/vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C zirconium/vendor/ImGuiFileDialog -f Makefile clean
	@${MAKE} --no-print-directory -C zirconium/vendor/spdlog -f Makefile clean
	@${MAKE} --no-print-directory -C zirconium/vendor/yaml-cpp -f Makefile clean
	@${MAKE} --no-print-directory -C zirconium/vendor/Box2D -f Makefile clean
	@${MAKE} --no-print-directory -C zirconium -f Makefile clean
	@${MAKE} --no-print-directory -C zirconium-Editor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   ImGui"
	@echo "   Glad"
	@echo "   ImGuiFileDialog"
	@echo "   SpdLog"
	@echo "   yaml-cpp"
	@echo "   Box2D"
	@echo "   zirconium"
	@echo "   zirconium-Editor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"